development: 
  adapter: postgresql
  encoding: unicode
  database: todo_list_development
  pool: 5
  host: localhost
  timeout: 5000
  username: james
  password: secret #is a password necesary?

test:
  adapter: postgresql
  encoding: unicode
  database: todo_list_test
  pool: 5
  host: localhost
  timeout: 5000
  username: james
  password: secret #is a password necesary?

